### ISSUE TITLE
Create Nice Icons

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#1]
Create nice looking set of icons and pictures.
Precondition: have some useful amount of functions implemented, to have a clear view of what is necessary.

- [x] launcher icon
- [x] logo
- [x] icon for "Select Activity"
- [x] icon for "Diary"

**Comment by sesam** [comment]
Something like 
![Potato clock](https://images-na.ssl-images-amazon.com/images/G/01/aplusautomation/vendorimages/3e71b98a-c1de-47bb-8e22-c2896f2198d8.jpg._CB323986676_.jpg)
but maybe more a ![calendar thing](http://www.cafepress.com/+potato+calendars)

**Comment by ramack** [comment]
Thanks for the suggestions even though I'm not yet convinced :-)
For the potato: it might be too constraint on gardening. Yes, I also give those kind of examples, but it should not be limited to this kind of activities. The calendar symbol is already dedicated to real calendar apps, so the task list is probably the closest...

**Comment by sesam** [comment]
Images proudly copy&pasted. Anyway for an icon you'd need vector, but showing this thread to someone on fiverrr, and a $5, could be all it takes to get some good vector gfx.

I looked in G Play, and found two apps with the same name:

- https://play.google.com/store/apps/details?id=com.origamitec.activitydiary  Similar, though targeted more as a life logging app. 

- https://play.google.com/store/apps/details?id=fr.inra.activitydiary  French research app. "This application is targeted to volunteers participating in clinical trials in the field of daily-living physical activities."

Maybe thinking up some other branding alternatives could be worthwhile. Some play on the name or purpose that would also more quickly explain the apps purpose. It's kind of a "long now" version of Skalman's Sleep and Eat watch. He's a confused toon that needs a reminder when it's time to eat and sleep, among other things... actually something I might try to use this app for. Among other things, like tracking when I washed bed linen (every 1-2 weeks, preferably in sunny weather and also airing out pillows etc). On the other hand, this app is not a habit-maker, and it's likely targeted for long term actions, like checking car tires (recommended: daily, what we do? don't want to consider it) or swapping tires before the season to to be stuck in the rush. There are also things to be said about helping yourself while also helping others; science says there are near mysterious advantages to expressing gratitude to others etc and a "light" version of this I'd imagine using this app for, but would not have that in the branding. I'll keep thinking on this.

**Comment by ramack** [comment]
Both apps you reference don't look very advanced...
You describe quite well what I am thinking about - even though in the first step it will be more like a "life logger" and later the target is to add some intelligence to become a "long-term task reminder". And I don't want it to be too aggressive... telling me each day with a notification that I shall swapping the tires in the next weeks is not a good idea. At the moment I think of mainly reminding indirectly by just sorting the activities in the view to select the current activity. Short-term tasks are often very present in my life such that it is not meaningful to remind (e. g. buy bread every 2nd or 3rd day) or they are single time actions so a traditional task management app is well suited. And I want to have it as kind of a diary to write down things to be able to search for "When did I do that last year? - I remember it was too early, but should I do it NOW this year or still wait?"

If you have good ideas for a better name or good pictures your suggestions are warmly welcome.

**Comment by ramack** [comment]
What do you say about the images in e9acadc746a8b1670ffbc520d5c45f97e71391cb ? Do you think this is acceptable? I don't really like them, but I have no better ideas...

**Comment by ramack** [comment]
so let's keep what we have right now...
If anyhow has some suggestions we can create a new ticket or directly a pull request.
