### ISSUE TITLE
Deleting a pics in an activity works on another activity.

### ISSUE THREAD

**Issue by mcyusuf** [ramack/ActivityDiary#118]
#### Expected behavior
Pics should be deleted from the activity clicked on.

#### Actual behavior
The pics doesn't delete on that particular activity, the delete works on pics in another activity at the top.

#### How to reproduce
Download app from fdroid.<br>
Open and select an activity, then add a pics to it.<br>
Do the same for another activity.<br>
Open the side menu and go to diary.<br>
Delete the pics attached to the former activity which would be below<br>
Notice the pics doesn't shows it's deleted,
but the latter one goes off as deleted. <br>

* App: Activity diary.     Fdroid store. Version 1.1.8
* Operating system: Android Nougat 7.0 on Tecno K7.

#### Recording Of The Bug
(https://youtu.be/yadELlLY6sU)
   

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/deleting-a-pics-in-an-activity-works-on-another-activity">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ramack** [comment]
OMG. Thanks for reporting. This is actually a heavy bug - will fix i for the next release.
