### ISSUE TITLE
App crashes when deleting one of more pics in an activity

### ISSUE THREAD

**Issue by mcyusuf** [ramack/ActivityDiary#119]
#### Expected behavior
A pics should be deleted amongst others under the same activity.

#### Actual behavior
Deleting a pic out of more than one pics in an activity crashes the app.

#### How to reproduce
Download the app from fdroid<br>
Open and create an activity<br>
Add more than one pics to the activity<br>
Open the side menu and go to diary<br>
Look for the activity and delete a pics from it<br>
App gets to crash at that instance<br>

* App: Activity Diary.   Fdroid version 1.1.8
* Operating system: Android Nougat 7.0 on Tecno K7

#### Recording Of The Bug
(https://youtu.be/fL7yDKjFdH0)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/app-crashes-when-deleting-one-of-more-pics-in-an-activity">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ramack** [comment]
This is for sure related to #118 and it is not robustly reproducible. Sometimes it also happens that the correct image is deleted, if the latest diary entry has less entries.
