### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by iqbalridha** [ramack/ActivityDiary#120]
This is the logo proposal i submitted for your application, sir. Tell me how you think sir. Thank you.
https://steemit.com/utopian-io/@iqbalridha/logo-design-proposal-for-activity-diary-app

**Comment by ramack** [comment]
I tried to answer also on utopian, but did not yet manage to get an account.

Anyhow, thanks a lot for the logo proposal, but to be honest, I had trouble to make the link between your logo and the app. With your explanation it makes sense and I can see the link, but would prefer a logo which contains the "timeline" in some form.

Also the flower I would not consider really important. - I have some gardening ideas in the description, and actually the trigger to implement this app came from that area, but I do not want to limit the use to that, so I think it is better to focus on the topics of timeline, attaching notes and pictures, maybe a book-like diary, etc...

**Comment by iqbalridha** [comment]
Thank you for your response sir, it's ok if you reject the logo, knowing what you need is enough for me. If you need anything you can contact me.
