### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [ramack/ActivityDiary#133]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by ramack** [comment]
That would be awsome I think the wiki would we the right place. Just start a new page.
Also the ['user manual'](https://github.com/ramack/ActivityDiary/wiki/Usage) in the wiki would benefit from caring more about it then I currently do.

**Comment by ramack** [comment]
Closed by 04e1ca9eda7cd7b3ccf753b7638bce6bdbd83f50 feel free to propose improvements.
