### ISSUE TITLE
App crashes while clicking on undo option.

### ISSUE THREAD

**Issue by pzdawood** [ramack/ActivityDiary#153]
### Actual behaviour
When I open the activity diary app and delete all activities and add new activity.i Add  Image and note.then i click on options botton and select diary options . Then i select recent added activity . Change start and end date then I  go back back to main menu and click on recent added activity and I want to undo this when I click on undo add crashes.
### How to reproduce
* Open the activity diary app.
* Delete all activities.
* Add new activity.
* Select photo and  write note.
* Click on options botton.
* Select diary option.
* Change start and end date.
* Go back to main menu.
* Click on recent added activity.
* Click on undo option.
* After clicking on undo option app crashes.
* Browser: Activity diary.
* Version: 1.2.2
* Operating system:7.1.2
### Recording of the bug
https://youtu.be/Yinv4TgwgAE

**Comment by ramack** [comment]
Thanks for the report. It doesn't seem to be an important use case but I will try to fix it for next release. Can you also share a stacktrace? A logcat or the crashreporting email? This would in that case help more than the video.

Thanks
