### ISSUE TITLE
allow editing start time of current activity

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#156]
tap on current activity in the main view should open the "HistoryDetailActivity" and / or the start time adjustment picker.

**Comment by contrapunctus-1** [comment]
Hi. I'm running v1.2.5 from F-Droid [1], I enabled 'Terminate activity by click', but tapping on the current activity button doesn't terminate it, nor does tapping on the activity in the activity selector.

[1] downloaded from their website - for some reason the client doesn't show the download button for this app, any ideas? Android v8.1, Nokia 6.1

**Comment by ramack** [comment]
Oh, did you try to disable it? It looks as I messed up the setting and inverted the logic...

About f-droid I have no idea what could be wrong. Does the fdroid client show version 1.2.5?

**Comment by contrapunctus-1** [comment]
Odd, I was trying to add this comment to #157 ...

Ah, you're right, the setting is inverted. 🙂

> About f-droid I have no idea what could be wrong. Does the fdroid client show version 1.2.5?

It does.

**Comment by ramack** [comment]
Doesn't matter too much. For f-droid: what do you get when you try to install the app there?

The issue you reported should be fixed already.

**Comment by contrapunctus-1** [comment]
Clearing F-Droid's data seemed to fix it. Thanks!
