### ISSUE TITLE
Scroll view when editing an entry

### ISSUE THREAD

**Issue by tschroeder13** [ramack/ActivityDiary#165]
Hey all,
When I edit an entry, the description section is over lapped by the keyboard and therefore not visible.
Would it be possible to use something like auto scrolling or similar?

Kind regards
Tobias

**Comment by ramack** [comment]
Thanks for the report.

This should be fixed already in 8b12bc32d2ac1fc0435b8f5daa58bec7e4d5de9d. Please confirm after next release is available. (v1.2.5 should be tagged this week).

**Comment by ramack** [comment]
@tschroeder13 v1.2.5 is available in play store and will popup in f-droid soon (usually a few days) - would be great if you could give it a try and close the issue if it is solved, or otherwise create some screenshot.

**Comment by ramack** [comment]
missing user feedback, I _believe_ it should be closed, so I'll do also with this ticket. Please reopen if the issue still occurs.
