### ISSUE TITLE
Ability to handle multiple activities at once

### ISSUE THREAD

**Issue by Ekleog** [ramack/ActivityDiary#174]
So I'm not really sure this is something that would be wanted, for reasons due to UI design. But I know I often do two things at the same time (eg. listening to a conference while coding, or similar things).

So I wonder whether it would make sense to handle logging multiple activities at the same time, so as to be able to later count the two times.

Then, a counter-argument would be that a brain can do a single thing at once, so… not sure it's actually a feature that would be useful and logical, just launching this idea in the air :)

**Comment by ramack** [comment]
I think this has some advantages, and I'd definitely like to implement it. See #17 and #24 

About how this should be visualized, how we want to start / finish activities, whether they should have perfect nesting (like refining some activities as harvesting as a sub-activity of gardening -> the hierarchical case), or arbitrary overlap like you listening to some audio while doing completely different things (close to but not exactly what is described as "background activity" in #17, or both should be allowed (and configurable in the activity whether it has a parent or can be done in background)... is open.

Convinces that this is useful in the long term I think also, that there are some higher priority tickets to work on first, but concrete ideas and PRs are still warmly welcome :-)

**Comment by Ekleog** [comment]
Yes, I get it's not high-priority at all :) Anyway, thank you for the feedback!

Closing in favor of #17 (exactly what I was thinking of) and #24 (which looks like a nice addition) :)
