### ISSUE TITLE
Improve Search: recent searches

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#187]
on starting search, directly provide search suggestions with the last search term
Maybe have 5 before typing and reduce as soon as some characters are types by only the matching ones and add the current search suggestions.

**Comment by ondri124** [comment]
Hello may I take this issue ?

**Comment by ramack** [comment]
For sure. Looking forward to review a PR. the number of 5 might be too big... just try what is good...

**Comment by ramack** [comment]
open is
- [ ] store the type of the search, show the matching icon and do the search exactly the same as initially
- [ ] configurable amount of recent search entries
- [ ] keep the recent search entries as long as they fit to the already typed text
