### ISSUE TITLE
README update?

### ISSUE THREAD

**Issue by sesam** [ramack/ActivityDiary#22]
Great (quick) job, this!

> Status
> 
> It is not yet doing anything useful, but feel free to contribute code, ideas and issues on https://github.com/ramack/ActivityDiary
> 
> Stay tuned.

Status update on the way? :)
If F-Droid supports Beta testing, or if you'd consider making it available as Beta on Play store, I'd be happy to test it and supply issues and maybe something more.

**Comment by ramack** [comment]
Would be great, if you could give it a try. It should be available in Play store in the alpha channel. - Shame on me, that it's first there and only afterwards in f-droid, but there it is just a few clicks without manual effort from G side - which is different in f-droid, there I will try to come up with a pull request for fdroiddata, but as it seems to go there directly in the "normal" repository without a possibilty to really tag it as alpha it would be a bit early to push it there...

I'm looking forward to read comments from you!

**Comment by sesam** [comment]
Thanks. I tried the expected link with no luck.

https://play.google.com/store/apps/details?id=de.rampro.activitydiary  not
found

According to
https://stackoverflow.com/questions/17659204/where-do-alpha-testers-download-google-play-android-apps
likely you need to invite me as alpha tester on my mail, which is on the
format firstname.lastname at gmail

Thanks // Simon Bohlin

On Nov 5, 2017 21:12, "Raphael Mack" <notifications@github.com> wrote:

Would be great, if you could give it a try. It should be available in Play
store in the alpha channel. - Shame on me, that it's first there and only
afterwards in f-droid, but there it is just a few clicks without manual
effort from G side - which is different in f-droid, there I will try to
come up with a pull request for fdroiddata, but as it seems to go there
directly in the "normal" repository without a possibilty to really tag it
as alpha it would be a bit early to push it there...

I'm looking forward to read comments from you!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ramack/ActivityDiary/issues/22#issuecomment-342001541>,
or mute the thread

**Comment by ramack** [comment]
You might want tog give it another try at https://play.google.com/apps/testing/de.rampro.activitydiary I just reconfigured the alpha test to be an "open" one. With that I would expect, that anyone can try it.

**Comment by sesam** [comment]
Congrats on 0.3. Will you push the release also to GPlay? Have a nice day

**Comment by ramack** [comment]
Should be there already... but it might take some time to be distributed. Dud you try the v0.2 there?

**Comment by sesam** [comment]
Going to https://play.google.com/apps/testing/de.rampro.activitydiary and then to https://play.google.com/store/apps/details?id=de.rampro.activitydiary&ah=JV0TWtegKm7gPmpPph88GBVtZSs I only see the first version 0.1. Maybe there's some additional button you need to click to distribute to all testers.

**Comment by ramack** [comment]
mh, here: https://play.google.com/store/apps/details?id=de.rampro.activitydiary I see the latest screenshots and also the release date Nov 16.

**Comment by sesam** [comment]
I've tried installing on 3 phones. On all, the app force closes immediately. But I'm happy I've seen the screenshots on GPlay now :). Looks promising!

**Comment by ramack** [comment]
mhh. It looks like there is some trouble with different library versions. I will try to release another version to see whether this fixes it...

**Comment by ramack** [comment]
Might be available. But for now you need to uninstall the app, before updating ;-(

**Comment by ramack** [comment]
Let me bump this again... v0.5 is out, now you should not even be required to uninstall older versions. Updating will silently drop existing data and recreate the database :-)

**Comment by sesam** [comment]
Works - thanks!

**Comment by ramack** [comment]
Oh great. Looking forward to you tickets 😃
