### ISSUE TITLE
Have a calendar view of activities

### ISSUE THREAD

**Issue by LeoK987** [ramack/ActivityDiary#223]
For past activities, in addition to current list view, it would nice to have them on a calendar view, showing visually at what time and how long every activity took place.

**Comment by ramack** [comment]
This is a good idea, that is already requested by #32, but I consider it not as critical for now, that's why it is not even scheduled to any upcoming release, but in the "future" milestone. But for sure I can include it earlier if it's important for you. Maybe you can even think of submitting a PR?
