### ISSUE TITLE
View statistics for specified day in a pie chart

### ISSUE THREAD

**Issue by vit1-irk** [ramack/ActivityDiary#233]
It will be the perfect way to analyze your daily activity

What did I do last day?
What did I do N days ago?

Currently activity statistics support only "last 7 days" overview and much more global patterns (like whole month/year). It will be good to see the pie chart for random day by picking the date on some kind of calendar widget.

If it is hard to implement, please, add at least "last day" entry in a time range picker
Thanks in advance

**Comment by ramack** [comment]
See also #215 I think it should not be a problem to support that.
