### ISSUE TITLE
publication

### ISSUE THREAD

**Issue by Dragonnishan** [ramack/ActivityDiary#275]
can I use your source code for my diary programme it is free?

**Comment by ramack** [comment]
I depends on your definition if free. The code is published under the terms of the GPLv3+, so yes, you are allowed to base your own app on that code, in theory even without asking. For sure it is good practice to ask before and to mention the original authors. And you also have to publish your code under the GPL in version 3 or later.

You can read all that in the source and the LICENSE file...

**Comment by ramack** [comment]
@Dragonnishan did you already take a decision? Would be great to get some feedback.

**Comment by Dragonnishan** [comment]
no, I did not take any decision, when I use your codings how can I use your licence,
 is it ok to identify your authorization in my application about menu and google store listening.

**Comment by ramack** [comment]
It is not "my" license in specific. It is the "GNU General Public License", I just applied it. It is worth to read it and browse the web a little about it. In a glimpse it means you are free to
- use the program for whatever you want
- analyze and adapt the program to your needs
- redistribute
- improve and publish the modified version
But that doesn't come for free as in "free" beer, you have to respect the copyright and mention the original authors. - In the app itself it is sufficient to mention that your project is based on ActivityDiary and give a link in addition to keeping the names of the contributors in source and UI.

And the probably biggest consequence come from the fact that the GPL is a "viral", copyleft license, which means, that you are allowed "combine" it only with compatible code. So you either have to apply the same or a "weaker" license to your code linked to it and also you can only choose libraries, that are following the same rules.

I hope that helps and explains a little about the license. I can also give a quick feedback when you published your stuff, but be aware, that I am not a lawyer...
