### ISSUE TITLE
Choose good color for new Activities

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#55]
Currently every new activity has the nice orange color. We should provide several default colors, and wisely select the next one to be chosen...

Any ideas for the algorithm how to find the text one? Just store the index of the last one that was selected? Or anything that is "far" from the current "mean" color?

**Comment by sesam** [comment]
maybe just a random color, and retry once if the random color is same as
most recent/adjacent to the new list item. might be tricky to check
adjacent list item without messing up the thread safety

**Comment by ramack** [comment]
I will try random color. But I fear that it doesn't look very nice... because the random colors might not (optically) fit together. But maybe we cam have some stored list of colors and randomly select one of those... 
Oh and if we want some nice distubution of colors we could even impact the probability of each color in the palette by the "mean distance" to the active colors...
Somehow I am also not happy about the current color picker because it doesn't allow giving a list of preselected palette.

**Comment by ramack** [comment]
This might be interesting http://devmag.org.za/2012/07/29/how-to-choose-colours-procedurally-algorithms/

https://stackoverflow.com/questions/9018016/how-to-compare-two-colors-for-similarity-difference

**Comment by ramack** [comment]
What do you think about the implementation?

**Comment by sesam** [comment]
Looks good!
