### ISSUE TITLE
Add option for persistent Notification

### ISSUE THREAD

**Issue by HorribleGeek** [ramack/ActivityDiary#77]
I left that app running for 4 hours without changing the activity. I realised this when I got your email otherwise it would have extended to 12 hrs or more.

Add option to show persistent notification, maybe just a simple one showing which activity is running and clicking on that will open the app.

This will force the app to run in background but will increase users interaction with the app. 

Otherwise I am sure there will be many like me who forget it once they set an activity.

https://imgur.com/a/BT40m

**Comment by HorribleGeek** [comment]
I love the way OpenTask shows it.
https://imgur.com/a/Rg6xE

I don't know how but there is no process running in the background but the notification is persistent and interactive.

F-Droid: https://f-droid.org/packages/org.dmfs.tasks/

**Comment by ramack** [comment]
Yes, notifications are a good idea. Thanks for proposing it. I think a persistent notification, showing the current activity could be good but it needs to be able to deactivate it in the settings. (I personally for example do not like those sticky notifications).

Together with auto switching of activities (see #18) it gets really interesting to have notifications. As soon as the likelihood for an activity to stay active goes down we can ask the user to select the next one (or keep the current for some more time) and if a new activity is so likely that the app even decides to automatically switch it, the user shall be notified and get the possibility to undo the new activity selection.

**Comment by HorribleGeek** [comment]
Yes! Maybe if the user is able to change history and add deadline for activites we can eliminate the need for persistent notification.
