### ISSUE TITLE
Add Italian Language 

### ISSUE THREAD

**Issue by DogeIlMeme** [ramack/ActivityDiary#81]
Add Italian Langage please

**Comment by ramack** [comment]
Thanks for requesting. This is very important to get an impression of what is important for the users! The problem I have is, that I do not speak Italian. Would you be willing to check a translation? Or even help translating? I fear, that by only using translation tools it would not read well for native speakers...

**Comment by ramack** [comment]
I created a project on crowdin: https://crowdin.com/project/activitydiary and did an tool based translation. Can you register there and check the Italian? Does it make sense like that?

In case that works I will ask Crowdin of an "Open Source" access, which is usable more than 10 Days as the current trial. So it would be really good if you could take a look within the coming week.

**Comment by ramack** [comment]
#86 is the one which seems to fix this issue...

**Comment by ramack** [comment]
In case you prefer an apk to install on a device for checking the translation tell me and I'll provide one.

**Comment by ramack** [comment]
You are invited to help translating. The currently available Italian translation is completely tool-based (aka google translate). Please join here https://crowdin.com/project/activitydiary/invite?d=q6m636u4b5t6535327b34313o433h3 so review and improve it.
