### ISSUE TITLE
slowdown

### ISSUE THREAD

**Issue by DogeIlMeme** [ramack/ActivityDiary#98]
In the new version I immediately noticed that the app was very slow

**Comment by ramack** [comment]
Thanks for the notice. It is a known issue,  and actually the main problem was, that the 1.1.7 beta version made it accidentally to the fdroid repo. I try to release a new version ASAP.

Regards,
Rapha

Am 22. Februar 2018 07:19:53 MEZ schrieb DogeIlMeme <notifications@github.com>:
>In the new version I immediately noticed that the app was very slow
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ramack/ActivityDiary/issues/98

--
WhatsApp? Nein aber XMPP/Jabber!
App: Conversations
Kontakt: ramack@rampro.de

**Comment by ramack** [comment]
closed by d644037c8cf51694b87b6cd33ea0fca18c87c9b8
